name = "aoc2025"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Aoc2025"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Aoc2025"

[[lean_exe]]
name = "Day01"
root = "Aoc2025.Day01"
