name = "aoc2025"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Aoc2025"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.25.2"

[[lean_lib]]
name = "Aoc2025"

[[lean_exe]]
name = "Day01"
root = "Aoc2025.Day01"

[[lean_exe]]
name = "Day02"
root = "Aoc2025.Day02"

[[lean_exe]]
name = "Day03"
root = "Aoc2025.Day03"

[[lean_exe]]
name = "Day04"
root = "Aoc2025.Day04"

[[lean_exe]]
name = "Day05"
root = "Aoc2025.Day05"

[[lean_exe]]
name = "Day06"
root = "Aoc2025.Day06"

[[lean_exe]]
name = "Day07"
root = "Aoc2025.Day07"